version: "2"
checks:
  argument-count:
    config:
      threshold: 5
plugins:
  duplication:
    enabled: true
    config:
      languages:
        php:
          patterns:
            - "app/**/*.php"
            - "!**/Repositories/*.php"
